name: CI & Push Docker Image

on:
  push:
    branches:
      - staging
      - master

jobs:
  build-and-push:
    name: Build, Tag & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build com Maven
        run: mvn clean package -DskipTests

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: flavinn/monitoramento-ambiental-api-mongodb:${{ github.ref_name }}

  robot-tests:
    name: Testes de API com Robot Framework
    runs-on: ubuntu-22.04  # fix para evitar problemas com Python 3.10
    needs: build-and-push

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Robot dependencies
        run: |
          cd robot-tests
          pip install -r requirements.txt

      - name: Start API container
        run: |
          docker run -d -p 8080:8080 flavinn/monitoramento-ambiental-api-mongodb:${{ github.ref_name }}
          sleep 10

      - name: Criar diretório de resultados
        run: mkdir -p robot-tests/tests/results

      - name: Run Robot Tests
        run: |
          cd robot-tests
          robot -d tests/results tests

      - name: Verificar arquivos gerados
        run: ls -R robot-tests/tests

      - name: Robot Reporter
        if: always()
        uses: joonvena/robotframework-reporter-action@v2.4
        with:
          gh_access_token: ${{ secrets.GITHUB_TOKEN }}
          report_path: robot-tests/tests/results

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Test Report
          path: robot-tests/tests/results
