name: CI & Push Docker Image

on:
  push:
    branches:
      - master
      - staging

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Build com Maven
        run: mvn clean package -DskipTests

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: flavinn/monitoramento-ambiental-api-mongodb:${{ github.ref_name }}