name: CI & Push Docker Image

# Dispara só em push para staging e master
on:
  push:
    branches:
      - staging
      - master

jobs:
  build-and-push:
    name: Build, Tag & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # 1) Puxa o código
      - name: Checkout do código
        uses: actions/checkout@v3

      # 2) Instala Java 17
      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # 3) Compila o JAR (sem testes)
      - name: Build com Maven
        run: mvn clean package -DskipTests

      # 4) Autentica no Docker Hub
      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 5) Builda e faz push da imagem com a tag igual ao nome da branch (staging ou master)
      - name: Build & Push Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: flavinn/monitoramento-ambiental-api-mongodb:${{ github.ref_name }}
