name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # ou qualquer branch na qual a geração dos arquivos estáticos ocorra

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do código
      - name: Checkout do código
        uses: actions/checkout@v3

      # Passo 2: Gerar os arquivos estáticos
      # Dependendo do que você precisa publicar, adicione aqui as etapas para compilar a documentação ou site.
      # Por exemplo, se for um projeto Java com Maven e você deseja publicar a documentação gerada pelo comando 'mvn site'
      # você pode fazer:
      # - name: Build Site
      #   run: mvn clean site
      #
      # Neste exemplo vamos assumir que os arquivos que queremos publicar já estão na pasta "public".

      # Caso precise copiar arquivos manualmente (ex.: copiando o README ou outros artefatos para "public"), você pode usar:
      # - name: Preparar arquivos para deploy
      #   run: |
      #     mkdir -p public
      #     cp -R docs/* public/
      
      # Passo 3: Deploy para o GitHub Pages usando a ação gh-pages
      - name: Deploy usando gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # Por padrão, a ação faz o push para a branch gh-pages
          # Caso deseje outra branch ou configurar customizações, veja a documentação da action.
